name: build

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    container:
      image: slim-toolchain:latest
      options: --privileged

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4

      - name: Checkout SlimLibraryPackager
        uses: actions/checkout@v4
        with:
          repository: greergan/SlimLibraryPackager
          path: SlimLibraryPackager

      - name: Update env
        working-directory: ${{ github.workspace }}
        run: |
          chmod +x ./SlimLibraryPackager/update_env.sh
          ./SlimLibraryPackager/update_env.sh

      - name: Build
        run: |
          make RELEASE_TYPE=Release SHARED_ONLY=OFF
