name: build

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    container:
      image: slim-toolchain
      options: --privileged

    steps:
      - name: Install Node (Required for Checkout)
        run: apt-get update && apt-get install -y nodejs
      - name: Checkout main repo
        uses: actions/checkout@v4

      - name: Checkout SlimLibraryPackager
        uses: actions/checkout@v4
        with:
          repository: greergan/SlimLibraryPackager
          path: SlimLibraryPackager
          ref: master

      - name: Update env
        run: |
          chmod +x ./SlimLibraryPackager/update_env.sh
          ./SlimLibraryPackager/update_env.sh

      - name: Build
        run: |
          make RELEASE_TYPE=Release SHARED_ONLY=OFF
