name: build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 1.0.1)'
        required: false

jobs:
  build-and-publish:
    runs-on: self-hosted
    container:
      image: slim-toolchain
      options: --privileged

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Checkout SlimLibraryPackager
        uses: actions/checkout@v4
        with:
          repository: greergan/SlimLibraryPackager
          path: SlimLibraryPackager
          ref: master

      - name: Determine Version
        run: |
          if [[ -n "${{ github.event.inputs.version }}" ]]; then
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          else
            echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
          fi

      - name: Update env
        run: |
          chmod +x ./SlimLibraryPackager/update_env.sh
          ./SlimLibraryPackager/update_env.sh

      - name: Build Packages
        run: |
          make packages

      - name: Publish to Forgejo Registry
        run: |
          REG_URL="${{ secrets.REGISTRY_URL }}"
          OWNER="${{ github.repository_owner }}"
          REPO="${{ github.event.repository.name }}"
          BASE_URL="$REG_URL/api/packages/$OWNER/generic/$REPO/$VERSION"
          
          for file in dist/*.deb dist/*.rpm; do
            if [ -f "$file" ]; then
              FILENAME=$(basename "$file")
              echo "Publishing $FILENAME to the registry..."
              
              curl --fail -sS \
                   --user "${{ secrets.REGISTRY_USER }}:${{ secrets.REGISTRY_TOKEN }}" \
                   --upload-file "$file" \
                   "$BASE_URL/$FILENAME"
            fi
          done

      - name: Link Package to Repository
        run: |
          URL="${{ secrets.REGISTRY_URL }}/api/v1/packages/${{ github.repository_owner }}/generic/${{ github.event.repository.name }}/${{ env.VERSION }}/repository"
          
          curl -X POST "$URL" \
            -H "Authorization: token ${{ secrets.REGISTRY_TOKEN }}" \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            -d "{\"repository_id\": ${{ github.repository_id }}}"